version: '3'

services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mongo-db

volumes:
  mongo-data:
