name: Build

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Zookeeper container
        run: |
          docker run -d --name zookeeper-security-devices -p 2181:2181 \
          confluentinc/cp-zookeeper:latest

      - name: Start Kafka container
        run: |
          docker run -d --name kafka-security-devices -p 9092:9092 \
              -e KAFKA_BROKER_ID=1 \
              -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
              -e KAFKA_LISTENERS=INTERNAL://kafka-security-devices:29092,EXTERNAL://:9092 \
              -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-security-devices:29092,EXTERNAL://localhost:9092 \
              -e KAFKA_ZOOKEEPER_CONNECT=zookeeper-security-devices:2181 \
              -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
              -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT \
              --link zookeeper-security-devices:zookeeper-security-devices \
              confluentinc/cp-kafka

      - name: Start Schema Registry container
        run: |
          docker run -d --name schema-registry-security-devices -p 8081:8081 \
            -e SCHEMA_REGISTRY_HOST_NAME=schema-registry \
            -e SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-security-devices:29092 \
            --link kafka-security-devices:kafka-security-devices \
            --link zookeeper-security-devices:zookeeper-security-devices \
            confluentinc/cp-schema-registry:latest

      - name: Start MongoDB container
        run: |
          docker run -d --name mongo -p 27017:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=root \
            -e MONGO_INITDB_ROOT_PASSWORD=root \
            -e MONGO_INITDB_DATABASE=mongo-db \
            mongo:latest

      - name: Start NATS container
        run: docker run -d --name nats -p 4222:4222 nats:latest

      - name: Start Redis container
        run: docker run -d --name redis -p 6379:6379 redis:latest

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and run checks
        run: ./gradlew build
